### ISSUE TITLE
Table header in LaTex

### ISSUE THREAD

**Issue by lepennec** [nutterb/pixiedust#69]
Hi,

I'm playing with your package and the default for a table with LaTex seems very different from the default in HTM: the header is not separated from the rest by an horizontal line and the table itself does not have a top and bottom line. I have been able to add the first horizontal line with
`sprinkle(part = "head", border = c("bottom"), border_color = "black"`
but did not find a way to add the two other lines (other than adding a top line for the header and a bottom line for the last line which is not very satisfactory...)

Erwan

**Comment by nutterb** [comment]
It's hard to know what you're seeing, but for illustration, this is the HTML table I get using the pure defaults

```r
library(pixiedust)

fit <- lm(mpg ~ wt + qsec + am, data = mtcars)

dust(fit,
     caption = "Linear Model")
```

![image](https://cloud.githubusercontent.com/assets/1848445/19322616/c4f3fc4a-9087-11e6-9e22-0263c310b276.png)

The LaTeX table is a very little bit different

![image](https://cloud.githubusercontent.com/assets/1848445/19322643/ddcd522a-9087-11e6-83ad-82e907685abe.png)


Because I think the presentation you are referring to is somewhat common, `pixiedust` has a standard medley function that can add these lines.  The code for it is

```r
library(pixiedust)

fit <- lm(mpg ~ wt + qsec + am, data = mtcars)

dust(fit,
     caption = "Linear Model") %>%
  medley_bw()
```

![image](https://cloud.githubusercontent.com/assets/1848445/19322689/0b0f67dc-9088-11e6-9350-adaed221ba35.png)

And the PDF output is

![image](https://cloud.githubusercontent.com/assets/1848445/19322749/41e762c8-9088-11e6-93e2-041c8f675320.png)


Note: my YAML content for the PDF output included

```
---
title: "Examples"
output: pdf_document
header-includes: 
- \usepackage{amssymb} 
- \usepackage{arydshln} 
- \usepackage{caption} 
- \usepackage{graphicx} 
- \usepackage{hhline} 
- \usepackage{longtable} 
- \usepackage{multirow} 
- \usepackage[dvipsnames,table]{xcolor} 
---
```

If you are getting different HTML output than I am, it's possible you have a CSS file loaded that is influencing your table layout (`pixiedust` won't override CSS settings unless explicitly instructed to do so).  Does that help get the presentation you want?

**Comment by lepennec** [comment]
Thank you for your help. My mistake was coming from the fact that in the vignette there was a
```
library(pixiedust)
dust(fit)
```
which produces a table with some borders. Looking at the source, it seems that this indeed due to some (defaullt?) CSS setting in the vignette...

**Comment by nutterb** [comment]
Oh, I've never noticed that.  I will look further into it, because I can see why that would be confusing.  

Thanks for pointing it out.

**Comment by lepennec** [comment]
It is indeed a default CSS setting for the vignettes..

**Comment by nutterb** [comment]
There's also the option to use

```
output: 
  rmarkdown::html_vignette:
    css: mystyles.css
```
(see: http://rmarkdown.rstudio.com/package_vignette_format.html)

[The actual CSS for `html_vignette`](https://github.com/rstudio/rmarkdown/blob/master/inst/rmarkdown/templates/html_vignette/resources/vignette.css)

For `pixiedust`, using a blank CSS file would be optimal.

**Comment by nutterb** [comment]
A css file has been added to the templates.  The vignettes will be corrected in the next release.
Thanks.
