### ISSUE TITLE
Pipes instead of plus

### ISSUE THREAD

**Issue by hadley** [nutterb/pixiedust#8]
FWIW I'd highly recommend using pipes instead of plus. It's generally easier to write (once you get the hang of it) and it works more naturally with pipelines from other packages.

**Comment by nutterb** [comment]
I had considered that, and decided to go with plus because I was too eager to see if I could make it work and not patient enough to figure out how to do the pipes.  Having done some reading now, I'm kicking myself for not having taken the hour of study it took me to get confident enough to try piping it.

In your experience, with such a young package, would you work out a way to deprecate the plus while adding the pipe, or would you just bite the bullet and make the change?

**Comment by hadley** [comment]
Just bite the bullet
